import { jsPDF } from "jspdf";
import { JURISDICTIONS, type StateCode, type Jurisdiction } from "./compliance";

function header(doc: jsPDF, title: string) {
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, 210, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text("HOA Rent Services", 14, 14);
  doc.setFontSize(10);
  doc.text(title, 196, 14, { align: "right" });
  doc.setTextColor(30, 41, 59);
}

function footer(doc: jsPDF, note: string) {
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(note, 14, 285);
  doc.text(new Date().toLocaleString(), 196, 285, { align: "right" });
}

function applyWatermark(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const cx = 105;
  const cy = 148;

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Draw vector house (watermark) using thin very light grey-blue lines (RGB 243, 245, 252)
    doc.setDrawColor(243, 245, 252);
    doc.setLineWidth(0.8);
    
    // Roof triangle
    doc.line(cx - 30, cy - 10, cx, cy - 35);
    doc.line(cx + 30, cy - 10, cx, cy - 35);
    doc.line(cx - 30, cy - 10, cx + 30, cy - 10);
    
    // Main walls box
    doc.line(cx - 24, cy - 10, cx - 24, cy + 25);
    doc.line(cx + 24, cy - 10, cx + 24, cy + 25);
    doc.line(cx - 24, cy + 25, cx + 24, cy + 25);
    
    // Door outline
    doc.line(cx - 8, cy + 25, cx - 8, cy + 7);
    doc.line(cx + 8, cy + 25, cx + 8, cy + 7);
    doc.line(cx - 8, cy + 7, cx + 8, cy + 7);
    
    // Text watermark: "HOA RENT SERVICES"
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(243, 245, 252);
    doc.text("HOA RENT SERVICES", cx, cy + 42, { align: "center" });
  }
}


export function downloadAppFeeReceipt(opts: {
  name: string;
  email: string;
  state: string;
  zip: string;
  amount: number;
  processor: string;
  disclosure: string;
}) {
  const doc = new jsPDF();
  header(doc, "Application Screening Fee Receipt");
  doc.setFontSize(20);
  doc.text("Application Screening Fee Receipt", 14, 38);
  doc.setFontSize(11);
  let y = 50;
  const rows: [string, string][] = [
    ["Applicant", opts.name],
    ["Email", opts.email],
    ["Jurisdiction", opts.state],
    ["ZIP", opts.zip],
    ["Processor", opts.processor],
    ["Receipt #", crypto.randomUUID().slice(0, 8).toUpperCase()],
  ];
  rows.forEach(([k, v]) => {
    doc.setTextColor(100, 116, 139);
    doc.text(k, 14, y);
    doc.setTextColor(30, 41, 59);
    doc.text(v, 70, y);
    y += 8;
  });

  y += 6;
  doc.setDrawColor(226, 232, 240);
  doc.line(14, y, 196, y);
  y += 10;
  doc.setFontSize(13);
  doc.text("Itemized Charges", 14, y);
  y += 8;
  doc.setFontSize(11);
  doc.text("Background screening fee", 14, y);
  doc.text(`$${opts.amount.toFixed(2)}`, 196, y, { align: "right" });
  y += 8;
  doc.setFont("helvetica", "bold");
  doc.text("Total Paid", 14, y);
  doc.text(`$${opts.amount.toFixed(2)}`, 196, y, { align: "right" });
  doc.setFont("helvetica", "normal");

  y += 16;
  doc.setFontSize(11);
  doc.text("Regional Disclosure", 14, y);
  y += 6;
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  const lines = doc.splitTextToSize(opts.disclosure, 180);
  doc.text(lines, 14, y);

  footer(doc, "This is a simulated receipt generated by HOA Rent Services.");
  applyWatermark(doc);
  doc.save(`application-screening-fee-receipt-${opts.state.toLowerCase()}.pdf`);
}

export function downloadHoldingAgreement(opts: { name: string; unit: string; start: string; end: string; amount: number; }) {
  const doc = new jsPDF();
  header(doc, "Reservation Holding Agreement");
  doc.setFontSize(18);
  doc.text("Reservation Holding Agreement", 14, 40);
  doc.setFontSize(11);
  doc.setTextColor(71, 85, 105);
  const body = `This Holding Deposit Agreement (the "Agreement") is entered into on ${new Date().toLocaleDateString()} between Morgan Landlord ("Landlord") and ${opts.name} ("Prospective Tenant") for the reservation of unit ${opts.unit} from ${opts.start} through ${opts.end}.

Prospective Tenant authorizes a holding deposit in the amount of $${opts.amount.toFixed(2)}, to be held pursuant to a 30-day manual authorization. Funds are non-debited until execution of a binding lease, at which time the holding deposit shall be applied to the first month's rent or refunded in full if Landlord fails to deliver the unit.

By electronically signing below, both parties acknowledge the terms of reservation and agree to the conditions of this holding period.`;
  doc.text(doc.splitTextToSize(body, 180), 14, 52);
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(11);
  doc.text(`Tenant signature: ${opts.name}`, 14, 200);
  doc.text(`Landlord signature: Morgan Landlord`, 14, 210);
  footer(doc, "Simulated agreement — for prototype demonstration only.");
  applyWatermark(doc);
  doc.save(`reservation-holding-agreement.pdf`);
}

export function downloadEscrowDisclosure(opts: {
  tenant: string;
  bankName: string;
  bankAddress: string;
  principal: number;
  apr: number;
  jurisdiction: Jurisdiction;
}) {
  const doc = new jsPDF();
  header(doc, "Security Deposit Escrow Disclosure");
  doc.setFontSize(18);
  doc.text("Security Deposit Escrow Disclosure", 14, 40);
  doc.setFontSize(11);
  let y = 56;
  const rows: [string, string][] = [
    ["Tenant", opts.tenant],
    ["Jurisdiction", `${opts.jurisdiction.name} (${opts.jurisdiction.code})`],
    ["Trust Bank", opts.bankName || "—"],
    ["Branch Address", opts.bankAddress || "—"],
    ["Principal Deposit", `$${opts.principal.toFixed(2)}`],
    ["Annual Interest Rate", `${(opts.apr * 100).toFixed(2)}%`],
    ["Projected 12-mo Interest", `$${(opts.principal * opts.apr).toFixed(2)}`],
    ["Refund Deadline", `${opts.jurisdiction.refundDeadline.days} ${opts.jurisdiction.refundDeadline.unit} days`],
  ];
  rows.forEach(([k, v]) => {
    doc.setTextColor(100, 116, 139);
    doc.text(k, 14, y);
    doc.setTextColor(30, 41, 59);
    doc.text(v, 80, y);
    y += 8;
  });
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const disclosure = `In accordance with ${opts.jurisdiction.name} landlord-tenant law, the security deposit referenced above is held in a segregated trust account and is not commingled with operating funds. Simple interest is computed as I = P × r × t.`;
  doc.text(doc.splitTextToSize(disclosure, 180), 14, y);
  footer(doc, "Simulated disclosure — for prototype demonstration only.");
  applyWatermark(doc);
  doc.save(`security-deposit-escrow-disclosure-${opts.jurisdiction.code.toLowerCase()}.pdf`);
}

export interface LeaseDownloadOpts {
  agreementDate?: string;
  landlordName?: string;
  tenantName?: string;
  bedrooms?: number;
  bathrooms?: number;
  parkingSpaces?: number;
  unitAddress?: string;
  storageSpaces?: string;
  furnishedStatus?: string;
  startDate?: string;
  endDate?: string;
  termTotalRent?: number;
  monthlyRent?: number;
  rentDueDay?: string;
  paymentMethod?: string;
  securityDeposit?: number;
  landlordNoticeAddress?: string;
  landlordNoticeEmail?: string;
  tenantNoticeAddress?: string;
  tenantNoticeEmail?: string;
  governingState?: string;
  disputeCounty?: string;
  petPolicy?: string;

  tenant?: string;
  unit?: string;
  start?: string;
  end?: string;
  rent?: number;
  pets?: string;
}

export function getLeaseSections(opts: LeaseDownloadOpts) {
  const agreementDate = opts.agreementDate || "May 21, 2026";
  const landlordName = opts.landlordName || "LEE SCOTT";
  const tenantName = opts.tenantName || opts.tenant || "LUCAS RICHARD";
  const bedrooms = opts.bedrooms !== undefined ? opts.bedrooms : 2;
  const bathrooms = opts.bathrooms !== undefined ? opts.bathrooms : 1;
  const parkingSpaces = opts.parkingSpaces !== undefined ? opts.parkingSpaces : 1;
  const unitAddress = opts.unitAddress || opts.unit || "174 Schools Dr, Camden, TN";
  const storageSpaces = opts.storageSpaces || "________";
  const furnishedStatus = opts.furnishedStatus || "fully furnished";
  const startDate = opts.startDate || opts.start || "May 23, 2026";
  const endDate = opts.endDate || opts.end || "November 23, 2026";
  const termTotalRent = opts.termTotalRent !== undefined ? opts.termTotalRent : 3900.00;
  const monthlyRent = opts.monthlyRent !== undefined ? opts.monthlyRent : (opts.rent !== undefined ? opts.rent : 660.00);
  const rentDueDay = opts.rentDueDay || "3rd";
  const paymentMethod = opts.paymentMethod || "Chime";
  const securityDeposit = opts.securityDeposit !== undefined ? opts.securityDeposit : 100.00;
  const landlordNoticeAddress = opts.landlordNoticeAddress || "174 Schools Dr, Camden, TN";
  const landlordNoticeEmail = opts.landlordNoticeEmail || "support.homeowneraassosications@gmail.com";
  const tenantNoticeAddress = opts.tenantNoticeAddress || "174 Schools Dr, Camden, TN";
  const tenantNoticeEmail = opts.tenantNoticeEmail || "lucas.nix06@icloud.com";
  const governingState = opts.governingState || "Arizona";
  const disputeCounty = opts.disputeCounty || "________";
  const petPolicy = opts.petPolicy || opts.pets || "________";

  const stateCode = Object.keys(JURISDICTIONS).find(
    (code) => JURISDICTIONS[code as StateCode].name.toLowerCase() === governingState.toLowerCase()
  ) as StateCode | undefined;
  const jur = stateCode ? JURISDICTIONS[stateCode] : undefined;

  const refundDays = jur ? jur.refundDeadline.days : 15;
  const refundUnit = jur ? jur.refundDeadline.unit : "calendar";
  const refundDaysWord = refundDays === 14 ? "fourteen (14)" : refundDays === 21 ? "twenty-one (21)" : refundDays === 30 ? "thirty (30)" : refundDays === 45 ? "forty-five (45)" : `${refundDays}`;

  const sections: [string, string][] = [
    [
      "",
      `This Lease Agreement (this "Agreement") is made this [[${agreementDate}]], by and among [[${landlordName}]] ("Landlord") and [[${tenantName}]] ("Tenant"). Each Tenant is jointly and severally liable to Landlord for full payment of rent and performance in accordance with all other terms of this Agreement. Each Landlord and Tenant may be referred to individually as a "Party" and collectively as the "Parties."`
    ],
    [
      "Premises",
      `The premises leased is an apartment with [[${bedrooms}]] bedroom(s) and [[${bathrooms}]] bathroom(s) and [[${parkingSpaces}]] parking space(s) located at [[${unitAddress}]] (the "Premises"). The entire property wherein the Premises is located shall be referred to as the "Project", inclusive of other residential units, parking areas and common areas. The Premises includes the following storage spaces: [[${storageSpaces || "None"}]]. The Premises is [[${furnishedStatus}]].`
    ],
    [
      "Agreement to Lease",
      `Landlord agrees to lease to Tenant and Tenant agrees to lease from Landlord, according to the terms and conditions set forth herein, the Premises.`
    ],
    [
      "Term",
      `This Agreement will be for a term beginning on [[${startDate}]] and ending on [[${endDate}]] (the "Term").`
    ],
    [
      "Rent",
      `Tenant will pay Landlord a rent for the Term of [[$${termTotalRent.toFixed(2)}]] payable in equal monthly installments of [[$${monthlyRent.toFixed(2)}]] ("Rent"). Rent will be payable in advance and due on the [[${rentDueDay}]] day of each month during the Term. Rent for any period during the Term which is for less than one month will be a pro rata portion of the monthly installment. Rent will be paid to Landlord at Landlord's address provided herein (or to such other places as directed by Landlord) by mail or in person by one of the following methods: [[${paymentMethod}]], and will be payable in U.S. Dollars.`
    ],
    [
      "Initial Payments",
      `Upon execution of this Agreement by Tenant and as a condition of consideration for acceptance by Landlord, Tenant shall pay to Landlord the following:
I. The first rent payment.
II. The last month Rent.
III. The Security Deposit. (See Section 7)`
    ],
    [
      "Additional Rent",
      `There may be instances under this Agreement where Tenant may be required to pay additional charges to Landlord. All such charges are considered additional rent under this Agreement and will be paid with the next regularly scheduled rent payment. Landlord has the same rights and Tenant has the same obligations with respect to additional rent as they do with rent.`
    ],
    [
      "Utilities",
      `Tenant is responsible for payment of all utility and other services for the Premises, with the exception of electric, gas, trash, heat, which will be paid for or provided by Landlord.`
    ],
    [
      "Security Deposit",
      `Upon signing this Agreement, Tenant will pay a security deposit in the amount of [[$${securityDeposit.toFixed(2)}]] to Landlord. The security deposit will be retained by Landlord as security for Tenant’s performance of its obligations under this Agreement. The security deposit may not be used or deducted by Tenant as the last month’s rent of the Term. Tenant will be entitled to a full refund of the security deposit if Tenant returns possession of the Premises to Landlord in the same condition as accepted, ordinary wear and tear excepted. Within [[${refundDaysWord} ${refundUnit}]] days after the termination of this Agreement, Landlord will return the security deposit to Tenant (minus any amount applied by Landlord in accordance with this section). Any reason for retaining a portion of the security deposit will be explained in writing. The security deposit will not bear interest while held by Landlord in accordance with applicable state laws and/or local ordinances.`
    ],
    [
      "Landlord's Failure to Give Possession",
      `In the event Landlord is unable to give possession of the Premises to Tenant on the start date of the Term, Landlord will not be subject to any liability for such failure, the validity of this Agreement will not be affected, and the Term will not be extended. Tenant will not be liable for rent until Landlord gives possession of the Premises to Tenant. Notwithstanding anything to the contrary, if Landlord does not deliver possession of the Premises within 3 days of the Start Date, Tenant may cancel this Agreement upon notice to Landlord and Landlord shall, within 7 business days, return all monies paid by Tenant to Landlord.`
    ],
    [
      "Holdover Tenancy",
      `Unless this Agreement has been extended by mutual written agreement of the Parties, there will be no holding over past the Term under the terms of this Agreement under any circumstances. If it becomes necessary to commence legal action to remove Tenant from the Premises, the prevailing Party will be entitled to attorney's fees and costs in addition to damages.`
    ],
    [
      "Use of Premises",
      `The Premises will be occupied only by Tenant and Tenant’s immediate family and used only for residential purposes. ${petPolicy !== "No pets allowed" && petPolicy !== "No pets" ? "Approved pets are permitted." : ""} Tenant will not engage in any objectionable conduct, including behavior which will make the Premises less fit to live in, will cause dangerous, hazardous or unsanitary conditions or will interfere with the rights of others to enjoy their property. Tenant will be liable for any damage occurring to the Premises and any damage to or loss of the contents thereof which is done by Tenant or Tenant’s guests or invitees.`
    ],
    [
      "Condition of the Premises",
      `Tenant has examined the Premises, including the appliances, fixtures and furnishings, and acknowledges that they are in good condition and repair, normal wear and tear excepted, and accepts them in its current condition.`
    ],
    [
      "Maintenance and Repairs",
      `Tenant will maintain the Premises, including the grounds and all appliances, fixtures and furnishings, in clean, sanitary and good condition and repair. Tenant will not remove Landlord’s appliances, fixtures, or furnishings from the Premises for any purpose. If repairs other than general maintenance are required, Tenant will notify Landlord for such repairs. In the event of default by Tenant, Tenant will reimburse Landlord for the cost of any repairs or replacement.`
    ],
    [
      "Military Clause",
      `In the event Tenant is, or hereafter becomes, a member of the United States Armed Forces (the “Military”) on extended active duty, and Tenant receives permanent change of station orders to depart from the area where the Premises is located or is relieved from active duty, retires or separates from the Military, or is ordered into Military housing, then Tenant may terminate this Agreement upon giving thirty (30) days written notice to Landlord. Tenant shall also provide to Landlord a copy of the official orders or a letter signed by Tenant’s commanding officer, reflecting the change which warrants termination under this Section. Tenant will pay prorated rent for any days Tenant occupies the dwelling past the first day of the month rent is due. Any security deposit will be promptly returned to Tenant, provided there are no damages to the Premises.`
    ],
    [
      "Reasonable Accommodations",
      `Landlord agrees to comply with all applicable laws providing equal housing opportunities, including making reasonable accommodations for known physical or mental limitations of qualified individuals with a disability, unless undue hardship would result. Tenant is responsible for making Landlord aware of any such required accommodations that are reasonable and will not impose an undue hardship. If Tenant discloses a disability and requests an accommodation, Landlord has the right to have a qualified healthcare provider verify the disability if the disability is not readily apparent, and Landlord has the right to use the qualified healthcare provider verifying the disability as a resource for providing the reasonable accommodation.`
    ],
    [
      "Sex Offender Registry",
      `Pursuant to law, information about specified registered sex offenders is made available to the public. Tenant understands and agrees that Tenant is solely responsible for obtaining any and all information contained in the state or national sex offender registry for the area surrounding the Premises, which can be obtained online or from the local sheriff’s department or other appropriate law enforcement officials. Depending on an offender’s criminal history, this information will include either the address at which the offender resides or the community of residence and zip code in which he or she resides.`
    ],
    [
      "Compliance",
      `Tenant agrees to comply with all applicable laws, ordinances, requirements and regulations of any federal, state, county, municipal or other authority.`
    ],
    [
      "Mechanics’ Lien",
      `Tenant understands and agrees that Tenant and anyone acting on Tenant’s behalf does not have the right to file for mechanic’s liens or any other kind of liens on the Premises. Tenant agrees to give actual advance notice to any contractors, subcontractors or suppliers of goods, labor or services that such liens are invalid. Tenant further agrees to take the additional steps necessary to keep the Premises free of any and all liens that may result from construction completed by or for Tenant.`
    ],
    [
      "Subordination",
      `With respect to the Premises, this Agreement is subordinate to any mortgage that now exists, or may be given later by Landlord.`
    ],
    [
      "Alterations",
      `Tenant will not make any alteration, addition or improvement to the Premises without first obtaining Landlord’s written consent. Any and all alterations, additions or improvements to the Premises are without payment to Tenant and will become Landlord’s property immediately on completion and remain on the Premises, unless Landlord requests or permits removal, in which case Tenant will return that part of the Premises to the same condition as existed prior to the alteration, addition or improvement. Tenant will not change any existing locks or install any additional locks on the Premises without first obtaining Landlord's written consent and without providing Landlord a copy of all keys.`
    ],
    [
      "Smoking",
      `Smoking of any kind is strictly prohibited on any part of the Premises. This prohibition applies to Tenant and any visitors, guests or other occupants on the Premises.`
    ],
    [
      "Pets",
      `Tenant is not allowed to have or keep any pets, even temporarily, on any part of the Premises, except for the following: [[${petPolicy}]]. The unauthorized presence of any pet will subject Tenant to penalties, damages, deductions and/or termination of this Agreement. Properly trained service animals that provide assistance to individuals with disabilities may be permitted on the Premises with the prior written consent of Landlord, which shall not be unreasonably withheld. Tenant will be responsible for the costs of de-fleaing, deodorizing and/or shampooing all or any portion of the Premises if a pet has been on the Premises at any time during the Term (whether with or without written consent of Landlord).`
    ],
    [
      "Fire and Casualty",
      `If the Premises are damaged by fire or other serious disaster or accident and the Premises becomes uninhabitable as a result, Tenant may immediately vacate the Premises and terminate this Agreement upon notice to Landlord. Tenant will be responsible for any unpaid rent or will receive any prepaid rent up to the day of such fire, disaster or accident. If the Premises are only partially damaged and inhabitable, Landlord may make full repairs and will do so within a prompt and reasonable amount of time. At the discretion of Landlord, the rent may be reduced while the repairs are being made.`
    ],
    [
      "Liability",
      `Landlord is not responsible or liable for any loss, claim, damage or expense as a result of any accident, injury or damage to any person or property occurring anywhere on the Premises, unless resulting from the negligence or willful misconduct of Landlord.`
    ],
    [
      "Assignment and Subletting",
      `Tenant will not assign this Agreement as to any portion or all of the Premises or make or permit any total or partial sublease or other transfer of any portion or all of the Premises.`
    ],
    [
      "Insurance Requirements",
      `Tenant will not do or permit to be done any act or thing that will increase the insurance risk under any policy of insurance covering the Premises. If the premium for such policy of insurance increases due to a breach of Tenant’s obligations under this Agreement, Tenant will pay the additional amount of premium as additional rent under this Agreement.`
    ],
    [
      "Right of Entry",
      `Landlord or its agents may enter the Premises at reasonable times to inspect the Premises, to make any alterations, improvements or repairs or to show the Premises to a prospective tenant, buyer or lender. In the event of an emergency, Landlord may enter the Premises at any time.`
    ],
    [
      "Surrender",
      `Tenant will deliver and surrender to Landlord possession of the Premises immediately upon the expiration of the Term or the termination of this Agreement, clean and in as good condition and repair as the Premises was at the commencement of the Term, reasonable wear and tear excepted.`
    ],
    [
      "Default",
      `In the event of any default under this Agreement, Landlord may provide Tenant a notice of default and an opportunity to correct such default. If Tenant fails to correct the default, other than a failure to pay rent or additional rent, Landlord may terminate this Agreement by giving a seven (7) day written notice. If the default is Tenant’s failure to timely pay rent or additional rent as specified in this Agreement, Landlord may terminate this Agreement by giving a seven (7) day written notice to Tenant. After termination of this Agreement, Tenant remains liable for any rent, additional late, costs, including costs to remedy any defaults, and damages under this Agreement.`
    ],
    [
      "Remedies",
      `If this Agreement is terminated due to Tenant’s default, Landlord may, in addition to any rights and remedies available under this Agreement and applicable law, use any dispossession, eviction or other similar legal proceeding available in law or equity.`
    ],
    [
      "Subordination",
      `This Agreement and Tenant’s right under it shall be subject and subordinate to the lien, operation and effect of each existing or future mortgage, deed of trust, ground lease and/or any other similar instrument of encumbrance covering any or all of the Premises, if any, and each renewal, modification, consolidation, replacement or extension thereof.`
    ],
    [
      "Condemnation",
      `If all or substantially all of the Premises are covered by a condemnation including the exercise of any power of eminent domain by a governmental authority, this Agreement shall terminate on the date possession of the Premises is taken by the condemning authority, and all rent under this Agreement shall be prorated and paid to such date. Landlord is entitled to collect from the condemning authority the entire amount of any award made in any proceeding. Tenant waives any right, title or interest which Tenant may have to any such award and agrees to not make any claim for the Term of this Agreement.`
    ],
    [
      "Hazardous Materials",
      `Tenant shall not keep on the Premises any item of a dangerous, flammable, or explosive character that might unreasonably increase the danger of fire or explosion on the Premises or that might be considered hazardous or extra hazardous by any responsible insurance company.`
    ],
    [
      "Notices",
      `All notices given under this Agreement must be in writing. A notice is effective upon receipt and shall be delivered in person, sent via certified or registered mail to the following addresses (or to another address that either Party may designate upon reasonable notice to the other Party):

Notices shall be sent to the Landlord at the following address:
[[${landlordNoticeAddress}]]
Email: [[${landlordNoticeEmail}]]

Notices shall be sent to the Tenant at the following address:
[[${tenantNoticeAddress}]]
Email: [[${tenantNoticeEmail}]]`
    ],
    [
      "Quiet Enjoyment",
      `If Tenant pays the rent and performs all other obligations under this Agreement, Tenant may peaceably and quietly hold and enjoy the Premises during the Term.`
    ],
    [
      "No Waiver",
      `No Party shall be deemed to have waived any provision of this Agreement or the exercise of any rights held under this Agreement unless such waiver is made expressly and in writing.`
    ],
    [
      "Severability",
      `If any provision of this Agreement is held to be invalid, illegal or unenforceable in whole or in part, the remaining provisions shall not be affected and shall continue to be valid, legal and enforceable as though the invalid, illegal or unenforceable part had not been included in this Agreement.`
    ],
    [
      "Successors and Assigns",
      `This Agreement will inure to the benefit of and be binding upon the Parties and their permitted successors and assigns.`
    ],
    [
      "Governing Law",
      `The terms of this Agreement and the rights and obligations of the Parties hereto shall be governed by and construed in accordance with the laws of the State of [[${governingState}]], without regard to its conflicts of laws provisions.`
    ],
    [
      "Disputes",
      `Any dispute arising from this Agreement shall be resolved in the courts of the County of [[${disputeCounty}]], State of [[${governingState}]] in accordance with the laws of the State of [[${governingState}]].`
    ],
    [
      "Attorneys' Fees",
      `If either Party brings legal action to enforce its rights under this Agreement, the prevailing party will be entitled to recover from the other Party its expenses (including reasonable attorneys' fees and costs) incurred in connection with the action and any appeal.`
    ],
    [
      "Amendments",
      `This Agreement may be amended or modified only by a written agreement signed by the Parties.`
    ],
    [
      "Counterparts",
      `This Agreement may be executed in one or more counterparts, each of which shall be deemed to be an original, and all of which together shall constitute one and the same document.`
    ],
    [
      "Headings",
      `The section headings herein are for reference purposes only and shall not otherwise affect the meaning, construction or interpretation of any provision in this Agreement.`
    ],
    [
      "Entire Agreement",
      `This Agreement constitutes the entire agreement between the Parties and supersedes and cancels all prior agreements of the Parties, whether written or oral, with respect to the subject matter.`
    ]
  ];

  return { sections, refundDays, refundUnit };
}

export function downloadLease(opts: LeaseDownloadOpts) {
  const doc = new jsPDF();
  
  const governingState = opts.governingState || "Arizona";
  const unitAddress = opts.unitAddress || opts.unit || "174 Schools Dr, Camden, TN";
  const landlordName = opts.landlordName || "LEE SCOTT";
  const tenantName = opts.tenantName || opts.tenant || "LUCAS RICHARD";

  // Margins & dimensions (margins: 20mm, printable width: 170mm)
  const margin = 20;
  const printWidth = 170;
  const fontSize = 9.5;
  const lineHeight = 4.5;
  let y = 46;

  // Title Block on First Page
  doc.setFont("times", "bold");
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42); // Slate-900
  doc.text("RESIDENTIAL LEASE AGREEMENT", 105, 25, { align: "center" });

  doc.setFontSize(11);
  doc.text(`STATE OF ${governingState.toUpperCase()}`, 105, 31, { align: "center" });

  // Double ruled line below title
  doc.setLineWidth(0.5);
  doc.setDrawColor(30, 41, 59); // Slate-800
  doc.line(margin, 36, 210 - margin, 36);
  doc.setLineWidth(0.15);
  doc.line(margin, 37.5, 210 - margin, 37.5);

  function checkPageBreak(neededHeight: number) {
    if (y + neededHeight > 265) {
      doc.addPage();
      y = 25; // below the running header
    }
  }

  // Token helper structures
  interface WordToken {
    text: string;
    highlight: boolean;
    hasSpaceAfter: boolean;
  }

  function parseToWords(text: string): WordToken[] {
    const tokens: WordToken[] = [];
    const regex = /\[\[(.*?)\]\]/g;
    let lastIndex = 0;
    let match;

    function addSegment(rawText: string, highlight: boolean) {
      const parts = rawText.split(/(\s+)/);
      parts.forEach((part) => {
        if (!part) return;
        if (/^\s+$/.test(part)) {
          if (tokens.length > 0) {
            tokens[tokens.length - 1].hasSpaceAfter = true;
          }
        } else {
          tokens.push({
            text: part,
            highlight,
            hasSpaceAfter: false
          });
        }
      });
    }

    while ((match = regex.exec(text)) !== null) {
      const normalText = text.substring(lastIndex, match.index);
      if (normalText) {
        addSegment(normalText, false);
      }
      addSegment(match[1], true);
      lastIndex = regex.lastIndex;
    }

    const remaining = text.substring(lastIndex);
    if (remaining) {
      addSegment(remaining, false);
    }

    return tokens;
  }

  function getWordWidth(word: WordToken): number {
    doc.setFont("times", word.highlight ? "bold" : "normal");
    doc.setFontSize(fontSize);
    return doc.getTextWidth(word.text);
  }

  function getSpaceWidth(): number {
    doc.setFont("times", "normal");
    doc.setFontSize(fontSize);
    return doc.getTextWidth(" ");
  }

  function wrapWordsWithIndent(
    words: WordToken[],
    maxLineWidth: number,
    firstLineIndent: number
  ): WordToken[][] {
    const lines: WordToken[][] = [];
    let currentLine: WordToken[] = [];
    let currentLineWidth = 0;
    const spaceWidth = getSpaceWidth();
    
    let isFirstLine = true;

    words.forEach((word) => {
      const wordWidth = getWordWidth(word);
      const addedWidth = currentLine.length > 0 ? spaceWidth : 0;
      const limit = isFirstLine ? (maxLineWidth - firstLineIndent) : maxLineWidth;

      if (currentLineWidth + addedWidth + wordWidth <= limit) {
        currentLine.push(word);
        currentLineWidth += addedWidth + wordWidth;
      } else {
        if (currentLine.length > 0) {
          lines.push(currentLine);
        }
        currentLine = [word];
        currentLineWidth = wordWidth;
        isFirstLine = false;
      }
    });

    if (currentLine.length > 0) {
      lines.push(currentLine);
    }

    return lines;
  }

  function renderLine(
    line: WordToken[],
    x: number,
    yPos: number,
    maxLineWidth: number,
    justify: boolean
  ) {
    const spaceWidth = getSpaceWidth();
    const wordWidths = line.map(w => getWordWidth(w));
    const totalWordsWidth = wordWidths.reduce((a, b) => a + b, 0);

    let gapWidth = spaceWidth;
    if (justify && line.length > 1) {
      const totalSpace = maxLineWidth - totalWordsWidth;
      gapWidth = totalSpace / (line.length - 1);
    }

    let currentX = x;
    line.forEach((word, idx) => {
      const wordWidth = wordWidths[idx];

      if (word.highlight) {
        doc.setFillColor(254, 243, 199); // bg-amber-100: RGB 254, 243, 199
        const rectHeight = (fontSize * 0.352778) * 1.25;
        const rectY = yPos - (fontSize * 0.352778) * 0.95;
        doc.rect(currentX - 0.4, rectY, wordWidth + 0.8, rectHeight, "F");
      }

      doc.setFont("times", word.highlight ? "bold" : "normal");
      doc.setFontSize(fontSize);
      
      if (word.highlight) {
        doc.setTextColor(120, 53, 4); // text-amber-900: RGB 120, 53, 4
      } else {
        doc.setTextColor(30, 41, 59); // text-slate-800: RGB 30, 41, 59
      }

      doc.text(word.text, currentX, yPos);
      currentX += wordWidth + gapWidth;
    });
  }

  const { sections } = getLeaseSections(opts);

  let sectionCounter = 1;
  sections.forEach(([title, body]) => {
    const sectionTitle = title ? `${sectionCounter}. ${title}` : "";
    if (title) sectionCounter++;

    checkPageBreak(8);

    if (sectionTitle) {
      doc.setFont("times", "bold");
      doc.setFontSize(10.5);
      doc.setTextColor(15, 23, 42); // Slate-900
      doc.text(sectionTitle, margin, y);
      y += 5.5;
    }

    const paragraphs = body.split("\n");
    paragraphs.forEach((pText) => {
      if (pText.trim() === "") {
        y += 2.5;
        return;
      }

      const words = parseToWords(pText);
      const firstLineIndent = 8;
      
      const shouldIndent = !pText.trim().startsWith("I.") && 
                           !pText.trim().startsWith("II.") && 
                           !pText.trim().startsWith("III.") &&
                           (!title || !title.includes("Notices")) &&
                           title !== "";

      const indentVal = shouldIndent ? firstLineIndent : 0;
      const lines = wrapWordsWithIndent(words, printWidth, indentVal);

      lines.forEach((line, lineIdx) => {
        const isLastLine = lineIdx === lines.length - 1;
        const isFirstLine = lineIdx === 0;
        
        const currentX = isFirstLine ? (margin + indentVal) : margin;
        const currentLimit = isFirstLine ? (printWidth - indentVal) : printWidth;
        
        const justify = !isLastLine && line.length > 1;

        checkPageBreak(lineHeight);
        renderLine(line, currentX, y, currentLimit, justify);
        y += lineHeight;
      });

      y += 2.5; // spacing after paragraph
    });

    y += 1.5; // spacing after section
  });

  // Render witness block & signatures
  checkPageBreak(50);
  y += 4;
  
  const witnessText = "IN WITNESS WHEREOF, the Parties hereto, individually or by their duly authorized representatives, have executed this Agreement as of the Effective Date.";
  const wWords = parseToWords(witnessText);
  const wLines = wrapWordsWithIndent(wWords, printWidth, 0);
  
  wLines.forEach((line) => {
    checkPageBreak(4.5);
    renderLine(line, margin, y, printWidth, false);
    y += 4.5;
  });
  
  y += 15;
  checkPageBreak(30);
  
  // Landlord signature line
  doc.setLineWidth(0.25);
  doc.setDrawColor(30, 41, 59); // Slate-800
  doc.line(margin, y, 95, y);
  doc.line(115, y, 210 - margin, y);
  
  doc.setFont("times", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Landlord Signature", margin, y + 4);
  
  doc.setFont("times", "bolditalic");
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text("/s/ " + landlordName, margin, y - 2); // digital signature representation
  
  doc.setFont("times", "bold");
  doc.setFontSize(9);
  doc.text(landlordName, 115, y + 4);
  doc.setFont("times", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Landlord Name", 115, y + 8);
  
  y += 20;
  checkPageBreak(30);
  
  // Tenant signature line
  doc.setLineWidth(0.25);
  doc.line(margin, y, 95, y);
  doc.line(115, y, 210 - margin, y);
  
  doc.setFont("times", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Tenant Signature", margin, y + 4);
  
  doc.setFont("times", "bolditalic");
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text("/s/ " + tenantName, margin, y - 2); // digital signature representation
  
  doc.setFont("times", "bold");
  doc.setFontSize(9);
  doc.text(tenantName, 115, y + 4);
  doc.setFont("times", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Tenant Name", 115, y + 8);

  // Post-pass running headers, running footers, and page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    
    // 1. Running Header (on pages > 1)
    if (i > 1) {
      doc.setFont("times", "italic");
      doc.setFontSize(8.5);
      doc.setTextColor(100, 116, 139); // Slate-500
      doc.text(`LEASE AGREEMENT - STATE OF ${governingState.toUpperCase()}`, margin, 15);
      
      doc.setDrawColor(203, 213, 225); // Slate-300
      doc.setLineWidth(0.2);
      doc.line(margin, 17, 210 - margin, 17); // Running header line
    }

    // 2. Running Footer (on all pages)
    doc.setDrawColor(203, 213, 225); // Slate-300
    doc.setLineWidth(0.2);
    doc.line(margin, 275, 210 - margin, 275); // Running footer line

    doc.setFont("times", "normal");
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139); // Slate-500
    
    // Left: Initials block
    doc.text("Landlord Initials: _______   Tenant Initials: _______", margin, 281);
    
    // Right: Page X of Y
    const pageStr = `Page ${i} of ${totalPages}`;
    doc.text(pageStr, 210 - margin, 281, { align: "right" });
  }

  applyWatermark(doc);
  doc.save(`residential-lease-agreement-${unitAddress.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}.pdf`);
}

export function downloadHandbook(tenant: string) {
  const doc = new jsPDF();
  header(doc, "Tenant Welcome Handbook");
  doc.setFontSize(18);
  doc.text("Welcome Home, " + tenant + "!", 14, 40);
  doc.setFontSize(11);
  doc.setTextColor(71, 85, 105);
  const body = `This handbook covers move-in procedures, maintenance request workflows, rent payment options, quiet hours, trash & recycling, package handling, emergency contacts, and your rights under your state's landlord-tenant act.

Please retain this document for the duration of your tenancy.`;
  doc.text(doc.splitTextToSize(body, 180), 14, 54);
  footer(doc, "HOA Rent Services Tenant Handbook");
  applyWatermark(doc);
  doc.save("tenant-welcome-handbook.pdf");
}

export function downloadRentalApplication(opts: {
  name: string;
  email: string;
  dob: string;
  ssn?: string;
  driverLicense: string;
  cellPhone: string;
  residenceStreet: string;
  residenceCity: string;
  residenceState: string;
  residenceZip: string;
  lastRentPaid: string;
  landlordPhone: string;
  employerName: string;
  companyName?: string;
  occupation: string;
  monthlyGrossPay: string;
  refName: string;
  refPhone: string;
  refRel: string;
  smoke: string;
  bankruptcy: string;
  felony: string;
  eviction: string;
}) {
  const doc = new jsPDF();
  
  // Set modern digital slate border styles (Tailwind slate-300: #CBD5E1 -> RGB 203, 213, 225)
  doc.setLineWidth(0.15);
  doc.setDrawColor(203, 213, 225);

  // Helper function to draw standard form cells with digital colors and precise text positioning
  function drawCell(
    x: number,
    y: number,
    w: number,
    h: number,
    label: string,
    value: string,
    isQuestion = false,
    labelSize = 5.5,
    valSize = 7.5,
    bgColor?: [number, number, number]
  ) {
    if (bgColor) {
      doc.setFillColor(bgColor[0], bgColor[1], bgColor[2]);
      doc.rect(x, y, w, h, "FD");
    } else {
      doc.rect(x, y, w, h);
    }
    
    if (label) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(labelSize);
      doc.setTextColor(100, 116, 139); // Softer Slate-500 color for form labels
      if (isQuestion) {
        const qLines = doc.splitTextToSize(label, w - 3);
        doc.text(qLines, x + 1.5, y + 2.8);
      } else {
        doc.text(label, x + 1.5, y + 2.8);
      }
    }
    if (value) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(valSize);
      doc.setTextColor(15, 23, 42); // Slate-900 for dark, professional, high-contrast values
      // Center vertically in cells without label (adding half height + 1.1mm baseline offset),
      // otherwise position near the bottom area (h - 1.8mm) to avoid touching the cell boundary.
      const valY = label ? y + h - 1.8 : y + (h / 2) + 1.1;
      doc.text(value, x + 1.5, valY);
    }
  }

  // --- PAGE 1 ---
  
  // Title & Header Information (Vibrant Brand Indigo: #4F46E5)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(79, 70, 229);
  doc.text("RENTAL APPLICATION FORM", 10, 16);
  doc.setTextColor(0, 0, 0); // Reset
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(71, 85, 105);
  doc.text("• Each adult (18 or older) must fill out a separate application", 100, 13);
  doc.text("• There is a refundable fee of $40/adult to apply", 100, 17);
  
  // PERSONAL INFORMATION TABLE
  let y = 22;
  
  // Split full name into First, Middle, Last
  const nameParts = opts.name.trim().split(/\s+/);
  const firstName = nameParts[0] || "";
  const middleName = nameParts.length > 2 ? nameParts.slice(1, -1).join(" ") : "";
  const lastName = nameParts.length > 1 ? nameParts[nameParts.length - 1] : "";

  // Row 1: Name parts, DOB, SSN, DL (White bg, default labels)
  drawCell(10, y, 30, 8, "First", firstName);
  drawCell(40, y, 25, 8, "Middle", middleName);
  drawCell(65, y, 35, 8, "Last", lastName);
  drawCell(100, y, 30, 8, "Birth Date", opts.dob);
  drawCell(130, y, 35, 8, "Social Security #", opts.ssn ? `***-**-${opts.ssn.replace(/[-\s]/g, "").slice(-4)}` : "—");
  drawCell(165, y, 35, 8, "Driver's License #", opts.driverLicense);
  
  y += 8;
  
  // Row 2: Any Other Names, Home Phone, Cell Phone
  drawCell(10, y, 90, 8, "Any Other Names You've Used In The Past", "—");
  drawCell(100, y, 45, 8, "Home Phone", "—");
  drawCell(145, y, 55, 8, "Cell Phone", opts.cellPhone);
  
  y += 8;
  
  // Row 3: All Other Proposed Occupants Header (Soft Blue/Indigo header shading)
  drawCell(10, y, 100, 6, "All Other Proposed Occupants", "", false, 6, 7.5, [238, 242, 255]);
  drawCell(110, y, 40, 6, "Birth Date", "", false, 6, 7.5, [238, 242, 255]);
  drawCell(150, y, 50, 6, "Relationship To Applicant", "", false, 6, 7.5, [238, 242, 255]);
  
  y += 6;
  
  // Rows 4-6: Occupant Rows (Placeholders for REV 9.1 structure)
  drawCell(10, y, 100, 5.5, "", "—");
  drawCell(110, y, 40, 5.5, "", "—");
  drawCell(150, y, 50, 5.5, "", "—");
  
  y += 5.5;
  drawCell(10, y, 100, 5.5, "", "—");
  drawCell(110, y, 40, 5.5, "", "—");
  drawCell(150, y, 50, 5.5, "", "—");
  
  y += 5.5;
  drawCell(10, y, 100, 5.5, "", "—");
  drawCell(110, y, 40, 5.5, "", "—");
  drawCell(150, y, 50, 5.5, "", "—");

  y += 5.5 + 4; // Add spacing before next section
  
  // RENTAL/RESIDENCE HISTORY (Indigo Accent Title)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(79, 70, 229);
  doc.text("RENTAL/RESIDENCE HISTORY", 10, y);
  doc.setTextColor(0, 0, 0); // Reset
  y += 2.5;

  // Header row for columns (Row Header W=60, Current W=45, Previous W=40, Prior W=45)
  drawCell(10, y, 60, 6, "", "", false, 6, 6.5, [238, 242, 255]);
  drawCell(70, y, 45, 6, "", "Current Residence", false, 6, 7.5, [238, 242, 255]);
  drawCell(115, y, 40, 6, "", "Previous Residence", false, 6, 7.5, [238, 242, 255]);
  drawCell(155, y, 45, 6, "", "Prior Residence", false, 6, 7.5, [238, 242, 255]);
  y += 6;

  // Rental History Fields (Left labels shaded in soft slate-50, W=60, font 6.5 to prevent overlap)
  const resHistoryRows = [
    ["Street Address", opts.residenceStreet, "—", "—"],
    ["City", opts.residenceCity, "—", "—"],
    ["State & Zip", `${opts.residenceState} ${opts.residenceZip}`.trim() || "—", "—", "—"],
    ["Last Rent Amount Paid", opts.lastRentPaid ? `$${opts.lastRentPaid}` : "—", "—", "—"],
    ["Owner/Manager and Phone Number", opts.landlordPhone, "—", "—"],
    ["Reason for leaving", "Relocation", "—", "—"],
    ["Is/Was rent paid in full?", "Yes", "—", "—"],
    ["Did you give notice?", "Yes", "—", "—"],
    ["Were you asked to move?", "No", "—", "—"],
    ["Name(s) in which utilities are now billed", opts.name, "—", "—"],
    ["Dates of Residency (From/To)", "Current", "—", "—"]
  ];

  resHistoryRows.forEach(([label, curr, prev, prior]) => {
    drawCell(10, y, 60, 5.5, "", label, false, 6, 6.5, [248, 250, 252]);
    drawCell(70, y, 45, 5.5, "", curr, false, 6, 7.5);
    drawCell(115, y, 40, 5.5, "", prev, false, 6, 7.5);
    drawCell(155, y, 45, 5.5, "", prior, false, 6, 7.5);
    y += 5.5;
  });

  y += 4; // Spacing

  // EMPLOYMENT HISTORY (Indigo Accent Title)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(79, 70, 229);
  doc.text("EMPLOYMENT HISTORY", 10, y);
  doc.setTextColor(0, 0, 0); // Reset
  y += 2.5;

  // Header row (Row Header W=60, Current W=45, Previous W=40, Prior W=45)
  drawCell(10, y, 60, 6, "", "", false, 6, 6.5, [238, 242, 255]);
  drawCell(70, y, 45, 6, "", "Current Employment", false, 6, 7.5, [238, 242, 255]);
  drawCell(115, y, 40, 6, "", "Previous Employment", false, 6, 7.5, [238, 242, 255]);
  drawCell(155, y, 45, 6, "", "Prior Employment", false, 6, 7.5, [238, 242, 255]);
  y += 6;

  // Employment Fields
  const empHistoryRows = [
    ["Employed By", opts.employerName, "—", "—"],
    ["Address", "—", "—", "—"],
    ["Employer's Phone", "—", "—", "—"],
    ["Occupation", opts.occupation, "—", "—"],
    ["Name of Supervisor", "—", "—", "—"],
    ["Monthly Gross Pay", opts.monthlyGrossPay ? `$${opts.monthlyGrossPay}` : "—", "—", "—"],
    ["Dates of Employment (From/To)", "Current", "—", "—"]
  ];

  empHistoryRows.forEach(([label, curr, prev, prior]) => {
    drawCell(10, y, 60, 5.5, "", label, false, 6, 6.5, [248, 250, 252]);
    drawCell(70, y, 45, 5.5, "", curr, false, 6, 7.5);
    drawCell(115, y, 40, 5.5, "", prev, false, 6, 7.5);
    drawCell(155, y, 45, 5.5, "", prior, false, 6, 7.5);
    y += 5.5;
  });

  y += 4; // Spacing

  // CREDIT HISTORY (Indigo Accent Title)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(79, 70, 229);
  doc.text("CREDIT HISTORY", 10, y);
  doc.setTextColor(0, 0, 0); // Reset
  y += 2.5;

  // Header row (Row Header W=60, Bank W=70, Balance W=60)
  drawCell(10, y, 60, 6, "", "", false, 6, 6.5, [238, 242, 255]);
  drawCell(70, y, 70, 6, "", "Bank/Institution Name", false, 6, 7.5, [238, 242, 255]);
  drawCell(140, y, 60, 6, "", "Balance On Deposit or Balance Owed", false, 6, 7.5, [238, 242, 255]);
  y += 6;

  const creditRows = [
    ["Savings Account", "—", "—"],
    ["Checking Account", "—", "—"],
    ["Credit Card", "—", "—"],
    ["Auto Loan", "—", "—"]
  ];

  creditRows.forEach(([label, bank, bal]) => {
    drawCell(10, y, 60, 5.5, "", label, false, 6, 6.5, [248, 250, 252]);
    drawCell(70, y, 70, 5.5, "", bank, false, 6, 7.5);
    drawCell(140, y, 60, 5.5, "", bal, false, 6, 7.5);
    y += 5.5;
  });

  y += 4; // Spacing

  // VEHICLES (Indigo Accent Title)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(79, 70, 229);
  doc.text("VEHICLES (Include vehicles belonging to other proposed occupants also)", 10, y);
  doc.setTextColor(0, 0, 0); // Reset
  y += 2.5;

  // Header
  drawCell(10, y, 40, 6, "", "Make", false, 6, 7.5, [238, 242, 255]);
  drawCell(50, y, 40, 6, "", "Model", false, 6, 7.5, [238, 242, 255]);
  drawCell(90, y, 30, 6, "", "Color", false, 6, 7.5, [238, 242, 255]);
  drawCell(120, y, 25, 6, "", "Year", false, 6, 7.5, [238, 242, 255]);
  drawCell(145, y, 55, 6, "", "License Plate", false, 6, 7.5, [238, 242, 255]);
  y += 6;

  // Vehicle Rows
  drawCell(10, y, 40, 5.5, "", "—");
  drawCell(50, y, 40, 5.5, "", "—");
  drawCell(90, y, 30, 5.5, "", "—");
  drawCell(120, y, 25, 5.5, "", "—");
  drawCell(145, y, 55, 5.5, "", "—");
  
  y += 5.5;
  drawCell(10, y, 40, 5.5, "", "—");
  drawCell(50, y, 40, 5.5, "", "—");
  drawCell(90, y, 30, 5.5, "", "—");
  drawCell(120, y, 25, 5.5, "", "—");
  drawCell(145, y, 55, 5.5, "", "—");

  // Footer info for Page 1
  doc.setFont("helvetica", "italic");
  doc.setFontSize(6);
  doc.setTextColor(148, 163, 184);
  doc.text("PLEASE PRINT", 10, 287);
  doc.text("REV 9.1", 192, 287, { align: "right" });


  // --- PAGE 2 ---
  doc.addPage();
  doc.setDrawColor(203, 213, 225); // Ensure slate borders are set on page 2
  y = 15;

  // REFERENCES & EMERGENCY CONTACTS (Indigo Accent Title)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(79, 70, 229);
  doc.text("REFERENCES & EMERGENCY CONTACTS", 10, y);
  doc.setTextColor(0, 0, 0); // Reset
  y += 2.5;

  // Header row (Row Header W=60, Doctor W=45, Lawyer W=40, Nearest Relative W=45)
  drawCell(10, y, 60, 6, "", "", false, 6, 6.5, [238, 242, 255]);
  drawCell(70, y, 45, 6, "", "Doctor", false, 6, 7.5, [238, 242, 255]);
  drawCell(115, y, 40, 6, "", "Lawyer", false, 6, 7.5, [238, 242, 255]);
  drawCell(155, y, 45, 6, "", "Nearest Relative Living Elsewhere", false, 6, 7.5, [238, 242, 255]);
  y += 6;

  const refRows = [
    ["Name", "—", "—", opts.refName || "—"],
    ["Street Address", "—", "—", "—"],
    ["City", "—", "—", "—"],
    ["State & Zip", "—", "—", "—"],
    ["Phone Number", "—", "—", opts.refPhone ? `${opts.refPhone} (${opts.refRel || "Relative"})` : "—"]
  ];

  refRows.forEach(([label, docVal, lawVal, relVal]) => {
    drawCell(10, y, 60, 5.5, "", label, false, 6, 6.5, [248, 250, 252]);
    drawCell(70, y, 45, 5.5, "", docVal, false, 6, 7.5);
    drawCell(115, y, 40, 5.5, "", lawVal, false, 6, 7.5);
    drawCell(155, y, 45, 5.5, "", relVal, false, 6, 7.5);
    y += 5.5;
  });

  // Note below references table
  y += 1.5;
  doc.setFillColor(248, 250, 252);
  doc.rect(10, y, 190, 8.5, "FD");
  doc.setFont("helvetica", "italic");
  doc.setFontSize(5.5);
  doc.setTextColor(100, 116, 139);
  const refDisclaimer = "By signing the application you grant us permission to communicate with all the contacts listed in this section in the event we can't locate you. Furthermore, if you abandon the apartment for any reason then you grant us permission to allow your relative listed above to remove all contents of the dwelling on your behalf.";
  doc.text(doc.splitTextToSize(refDisclaimer, 187), 11.5, y + 2.5);
  
  y += 8.5 + 4; // Spacing

  // GENERAL INFORMATION (Indigo Accent Title)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(79, 70, 229);
  doc.text("GENERAL INFORMATION", 10, y);
  doc.setTextColor(0, 0, 0); // Reset
  y += 2.5;

  // Question blocks
  // Row 1
  drawCell(10, y, 65, 10, "Have you ever been served a late rent notice?", "No", true);
  drawCell(75, y, 65, 10, "Do any of the people who would be living in the apartment smoke?", opts.smoke || "No", true);
  drawCell(140, y, 60, 10, "How long do you think you would be renting from us?", "2 Years", true);
  y += 10;

  // Row 2
  drawCell(10, y, 65, 10, "Have you ever filed for bankruptcy? If so, when?", opts.bankruptcy || "No", true);
  drawCell(75, y, 65, 10, "When would you be able to move in?", "Immediate", true);
  drawCell(140, y, 60, 10, "Have you ever been convicted of a felony?", opts.felony || "No", true);
  y += 10;

  // Row 3
  drawCell(10, y, 65, 10, "Have you ever been served an eviction notice? If so, when?", opts.eviction || "No", true);
  drawCell(75, y, 125, 10, "How many pets do you have (list Type, Breed, approx Weight & Age)?", "None", true);
  y += 10;

  // Row 4 (Full width)
  drawCell(10, y, 190, 11, "Have you had any reoccurring problems with your current apartment or landlord? If yes, please explain:", "No", true);
  y += 11;

  // Row 5 (Full width)
  drawCell(10, y, 190, 11, "Why are you moving from your current address?", "Relocating for proximity to jobs & amenities.", true);
  y += 11;

  // Row 6 (Full width)
  drawCell(10, y, 190, 11, "List any verifiable sources and amounts of income you wish to have considered (optional):", "Employment salary.", true);
  y += 11;

  // Row 7 (Full width)
  drawCell(10, y, 190, 13, "If you were to run into financial difficulty in the future and couldn't come up with the money to pay the rent, do you know someone that would loan you the money? If so, provide the person's name, address, & phone # so that we can use them as a reference for you.", opts.refName ? `${opts.refName} (${opts.refPhone})` : "—", true);
  y += 13;

  // Row 8 (Full width)
  drawCell(10, y, 190, 11, "Have you been a party to a lawsuit in the past? If yes, please explain why:", "No", true);
  y += 11;

  // Row 9 (Full width)
  drawCell(10, y, 190, 11, "We may run a credit check and a criminal background check. Is there anything negative we will find that you want to comment on?", "No", true);
  y += 11;

  // Row 10
  drawCell(10, y, 95, 10, "How did you hear about this apartment?", "Online Listing", true);
  drawCell(105, y, 95, 10, "Do you have an e-mail address we can reach you at?", opts.email, true);
  y += 10;

  // Row 11 (Full width)
  drawCell(10, y, 190, 13, "Do you know of anybody else looking for an apartment? Please provide their name and number. If you refer a friend and you each end up renting separate apartments from us then we will pay you a referral reward.", "—", true);
  y += 13;

  y += 4; // Spacing

  // Agreement & Authorization Signature (Indigo Accent Title)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(79, 70, 229);
  doc.text("Agreement & Authorization Signature", 10, y);
  doc.setTextColor(0, 0, 0); // Reset
  y += 2.5;

  // Drawing Agreement Box
  doc.rect(10, y, 190, 42);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(50, 50, 50);
  const authParagraph = "I believe that the statements I have made are true and correct. I hereby authorize a credit and/or criminal check to be made, verification of information I provided and communication with any and all names listed on this application. I understand that any discrepancy or lack of information may result in the rejection of this application. I understand that this is an application for an apartment and does not constitute a rental or lease agreement in whole or part. I further understand that there is a refundable fee to cover the cost of processing my application and I am entitled to a refund if I don't get the apartment. Any questions regarding rejected applications must be submitted in writing and accompanied by a self-addressed stamped envelope.";
  doc.text(doc.splitTextToSize(authParagraph, 186), 12, y + 4.5);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(0, 0, 0);
  doc.text(`Signature: /s/ ${opts.name}`, 12, y + 26);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 130, y + 26);
  
  // Underlines for signature fields
  doc.line(25, y + 27.5, 110, y + 27.5);
  doc.line(138, y + 27.5, 185, y + 27.5);

  // Footer info for Page 2
  doc.setFont("helvetica", "italic");
  doc.setFontSize(6);
  doc.setTextColor(148, 163, 184);
  doc.text("PLEASE PRINT", 10, 287);
  doc.text("REV 9.1", 192, 287, { align: "right" });

  applyWatermark(doc);
  doc.save(`rental-application-form-${opts.name.replace(/\s+/g, "-").toLowerCase()}.pdf`);
}
