/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityDepositRouteImport } from './routes/security-deposit'
import { Route as RentLedgerRouteImport } from './routes/rent-ledger'
import { Route as LeaseSigningRouteImport } from './routes/lease-signing'
import { Route as HoldingFeeRouteImport } from './routes/holding-fee'
import { Route as AppFeeRouteImport } from './routes/app-fee'
import { Route as AdminPanelRouteImport } from './routes/admin-panel'
import { Route as AdminComplianceRouteImport } from './routes/admin-compliance'
import { Route as IndexRouteImport } from './routes/index'

const SecurityDepositRoute = SecurityDepositRouteImport.update({
  id: '/security-deposit',
  path: '/security-deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const RentLedgerRoute = RentLedgerRouteImport.update({
  id: '/rent-ledger',
  path: '/rent-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaseSigningRoute = LeaseSigningRouteImport.update({
  id: '/lease-signing',
  path: '/lease-signing',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingFeeRoute = HoldingFeeRouteImport.update({
  id: '/holding-fee',
  path: '/holding-fee',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFeeRoute = AppFeeRouteImport.update({
  id: '/app-fee',
  path: '/app-fee',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin-panel',
  path: '/admin-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplianceRoute = AdminComplianceRouteImport.update({
  id: '/admin-compliance',
  path: '/admin-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-compliance': typeof AdminComplianceRoute
  '/admin-panel': typeof AdminPanelRoute
  '/app-fee': typeof AppFeeRoute
  '/holding-fee': typeof HoldingFeeRoute
  '/lease-signing': typeof LeaseSigningRoute
  '/rent-ledger': typeof RentLedgerRoute
  '/security-deposit': typeof SecurityDepositRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-compliance': typeof AdminComplianceRoute
  '/admin-panel': typeof AdminPanelRoute
  '/app-fee': typeof AppFeeRoute
  '/holding-fee': typeof HoldingFeeRoute
  '/lease-signing': typeof LeaseSigningRoute
  '/rent-ledger': typeof RentLedgerRoute
  '/security-deposit': typeof SecurityDepositRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-compliance': typeof AdminComplianceRoute
  '/admin-panel': typeof AdminPanelRoute
  '/app-fee': typeof AppFeeRoute
  '/holding-fee': typeof HoldingFeeRoute
  '/lease-signing': typeof LeaseSigningRoute
  '/rent-ledger': typeof RentLedgerRoute
  '/security-deposit': typeof SecurityDepositRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-compliance'
    | '/admin-panel'
    | '/app-fee'
    | '/holding-fee'
    | '/lease-signing'
    | '/rent-ledger'
    | '/security-deposit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-compliance'
    | '/admin-panel'
    | '/app-fee'
    | '/holding-fee'
    | '/lease-signing'
    | '/rent-ledger'
    | '/security-deposit'
  id:
    | '__root__'
    | '/'
    | '/admin-compliance'
    | '/admin-panel'
    | '/app-fee'
    | '/holding-fee'
    | '/lease-signing'
    | '/rent-ledger'
    | '/security-deposit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminComplianceRoute: typeof AdminComplianceRoute
  AdminPanelRoute: typeof AdminPanelRoute
  AppFeeRoute: typeof AppFeeRoute
  HoldingFeeRoute: typeof HoldingFeeRoute
  LeaseSigningRoute: typeof LeaseSigningRoute
  RentLedgerRoute: typeof RentLedgerRoute
  SecurityDepositRoute: typeof SecurityDepositRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security-deposit': {
      id: '/security-deposit'
      path: '/security-deposit'
      fullPath: '/security-deposit'
      preLoaderRoute: typeof SecurityDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-ledger': {
      id: '/rent-ledger'
      path: '/rent-ledger'
      fullPath: '/rent-ledger'
      preLoaderRoute: typeof RentLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lease-signing': {
      id: '/lease-signing'
      path: '/lease-signing'
      fullPath: '/lease-signing'
      preLoaderRoute: typeof LeaseSigningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holding-fee': {
      id: '/holding-fee'
      path: '/holding-fee'
      fullPath: '/holding-fee'
      preLoaderRoute: typeof HoldingFeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-fee': {
      id: '/app-fee'
      path: '/app-fee'
      fullPath: '/app-fee'
      preLoaderRoute: typeof AppFeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel': {
      id: '/admin-panel'
      path: '/admin-panel'
      fullPath: '/admin-panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-compliance': {
      id: '/admin-compliance'
      path: '/admin-compliance'
      fullPath: '/admin-compliance'
      preLoaderRoute: typeof AdminComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminComplianceRoute: AdminComplianceRoute,
  AdminPanelRoute: AdminPanelRoute,
  AppFeeRoute: AppFeeRoute,
  HoldingFeeRoute: HoldingFeeRoute,
  LeaseSigningRoute: LeaseSigningRoute,
  RentLedgerRoute: RentLedgerRoute,
  SecurityDepositRoute: SecurityDepositRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
